config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

    root to: 'posts#index'
    resources :posts do
      collection do
          post :confirm
      end
      member do
        patch :edit_confirm
      end
    end
    
    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :text,length: { in: 1..140 }
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 30}
    validates :email, presence: true, length: { maximum: 255}, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post,only: [:destroy, :update]
  
  def index
    @posts = Post.all
  end
    
  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end
  
  def confirm
    # @post = Post.new(post_params)
    @post = current_user.posts.build(post_params)
    if @post.invalid?
        render 'new'
    end
  end
  
  def edit_confirm
    @post = current_user.posts.build(post_params)
    if @post.valid?
        render 'edit_confirm'
    end
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    # @post = current_user.posts.build(post_params)
    if @post.save
        redirect_to posts_path, notice:"投稿しました！"
    else
        render 'confirm'
    end
  end
  
  def edit
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.find(params[:id])
    end
  end
  
  def destroy
    # @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice:"削除しました"
  end
  
  def update
    # @post = Post.find(params[:id])
    @post.user_id = current_user.id
    # @post = current_user.posts.build(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, notice:"編集しました！"
    else
      render 'edit'
    end
  end
  
  private
  
  def post_params
      params.require(:post).permit(:text, :image, :image_cache)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  
  def show
    @user =User.find(params[:id])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamFb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
             <span class="sr-only">メニュー</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
          <%= link_to 'FB', posts_path, class: "navbar-brand" %>
        </div>
 
  <div id="gnavi" class="collapse navbar-collapse">
    <ul class="nav navbar-nav  navbar-left">
      <li><%= link_to '新規投稿', new_post_path %></li>
    </ul>
    <ul class="nav navbar-nav  navbar-right">
     <% if logged_in? %>
       <li><%= link_to "Profile", user_path(current_user.id) %></li>
       <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
     <% else %>
       <li><%= link_to "Sign up", new_user_path %></li>
       <li><%= link_to "Login", new_session_path %></li>
     <% end %>
    </ul>
  </div>
</nav>
    
    <%= yield %>
      </div>
      
     </div><!-- /.container-fluid -->
    </nav>
  </body>
</html>

app/views/posts/confirm.html.erb
<h1>以下の内容で投稿する</h1>
<%= form_with(model: @post, url:posts_path, local: true, method: :post ) do |form| %>

    
     <%= form.hidden_field :text %>
     
     <% if @post.image.url.present? %>
      <%= image_tag(@post.image.url) %>
    <% end %>
     <%= form.hidden_field :image_cache %>
     
    <p><%= @post.text %></p>
    <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model: @post, url: new_post_path, local: true,method: :get) do |form| %>
    <%= form.hidden_field :text %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/posts/edit.html.erb
<h1>編集画面</h1>
<%= notice %>
<%= form_with(model: @post, url:edit_confirm_post_path, local: true, method: :patch ) do |form| %>
  <%= form.label :text %>
  <%= form.text_field :text %>
  
  <%= form.label :image %>
  <%= image_tag(@post.image.url, size: "300x300") if @post.image.url %>
  <%= form.file_field :image %>
  
  <%= form.submit %>
<% end %>

<!--<%= link_to 'トップに戻る', posts_path %>-->

app/views/posts/edit_confirm.html.erb
<h1>以下の内容で投稿する</h1>
<%= form_with(model: @post, url:post_path, local: true, method: :patch ) do |form| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
            <h2><%= @post.errors.count %>件のエラーがあります</h2>
            <ul>
              <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
    <% end %>
  <%= form.hidden_field :text %>
    <p><%= @post.text %></p>
 
  <%= form.hidden_field :image_cache %>
    <% if @post.image.url.present? %>
      <%= image_tag(@post.image.url, size: "300x300") %>
    <% end %>
  
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model: @post, url: edit_post_path, local: true,method: :get) do |form| %>
    <%= form.hidden_field :text %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<%= notice %>
<!--<table>-->
<!--<% @posts.each do |post| %>-->
<!--  <tr>-->
<!--    <td> <%= post.text %></td>-->
<!--    <% if post.image.url.present? %>-->
<!--    <td> <%= image_tag (post.image.url) %></td>-->
<!--    <% end %>-->
<!--    <td> <%= post.user.name %></td>-->
<!--    <td><%= link_to '編集する', edit_post_path(post.id), method: :get %></td>-->
<!--    <td><%= link_to '削除する', post_path(post.id), method: :delete, data: {confirm: '本当に削除していいですか？'} %></td>-->
<!--  </tr>-->
<!--<% end %>-->
<!--</table>--

<div class="jumbotron">
  <h1>画像とテキストを投稿しよう！</h1>
  <p>FBは画像とテキストを投稿できるサイトです。</p>
  <% if logged_in? %>
  <p><%= link_to 'いますぐ投稿！', new_post_path, class:"btn btn-primary btn-lg" %></p>
  <% else %>
  <p><%= link_to 'アカウントを作る', new_user_path, class:"btn btn-primary btn-lg" %></p>
  <% end %>
</div>

<div class="row">
  <% @posts.each do |post| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
         <% if post.image.url.present? %>
         <%= image_tag (post.image.url) %>
        <% end %>
      <div class="caption">
        <h3>投稿者：<%= post.user.name %></h3>
        <p>テキスト：<%= post.text %></p>
        <% if current_user.present? %>
        <p><%= link_to '編集する', edit_post_path(post.id), method: :get, class:"btn btn-primary" %>
        <% end %>
        <%= link_to '削除する', post_path(post.id), method: :delete, data: {confirm: '本当に削除していいですか？'}, class:"btn btn-default" %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>


<!--<%= link_to 'アカウントを作る', new_user_path %>-->

app/views/posts/new.html.erb
<h1>投稿画面</h1>
<%= notice %>
<%= form_with(model: @post, url:confirm_posts_path, local: true, method: :post ) do |form| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
            <h2><%= @post.errors.count %>件のエラーがあります</h2>
            <ul>
            <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
  <%= form.label :text %>
  <%= form.text_field :text %>
  
  <%= form.label :image %>
  <%= form.file_field :image %>
  <%= image_tag(@post.image.url) if @post.image.url %>
  
  <%= form.submit %>
<% end %>

<!--<%= link_to 'トップに戻る', posts_path %>-->
<!--<%= link_to 'トップに戻る', posts_path %>-->

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id = "error_explanation" >
      <h2>The form contains<%= pluralize(@user.errors.count, "error") %></h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :email %>
  <%= f.text_field :email %>
  
  <%= f.label :password %>
  <%= f.password_field :password %>
  
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.submit "アカウントを作る" %>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス：<%= @user.email %></p>

<%= link_to 'トップに戻る', posts_path %>